Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/04/2023
Var
// Seção de Declarações das variáveis 
n1, n2, s: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("informe um numero: ")
leia (n1)
escreval ("informe um numero: ")
leia (n2)
s <- n1 + n2
escreva ("a soma e: " , s)

Fimalgoritmo